### ISSUE TITLE
Bad error message on sidecar mismatch parentheses

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#616] opened 2023-02-22 12:51 UTC
@IanCa 

The following JSON sidecar has a missing closing parenthesis on `left_press`:

```
{
    "event_type": {
        "HED": {
 
            "left_press": "Agent-action, Participant-response, (Press, (Index-finger, (Right-side-of, Body))",
            "right_press": "Agent-action, Participant-response",
            "show_face": "Sensory-event, Experimental-stimulus, Visual-presentation, Face"
        }
    }
}
```
Sidecar validation gives the following error:

```
Column 'event_type':
	Key: left_press
		ERROR: No HED string found for Value or Category column.
```

The error should be `PARENTHESES_MISMATCH`.  Could you look at this?

**Comment by IanCa** [comment] 2023-02-22 16:45
This is a duplicate of 
https://github.com/hed-standard/hed-python/issues/546

**Closed** 2023-03-31 16:59 UTC
